
spring:
  application:
    name: swing-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    password:
    username:
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key:
      chat:
        options:
          model: deepseek-chat
server:
  port: 28081